[alias]
r = "run --release --quiet --"

extract = "r extract"
x = "extract"

pack = "r pack"
p = "pack"

read-lines = "r read-lines"
rl = "read-lines"

extract-dialogues = "r extract-dialogues"
xd = "extract-dialogues"

repack-dialogues = "r repack-dialogues"
rd = "repack-dialogues"
